### ISSUE TITLE
Folder names in README.md should end with "/"

### ISSUE THREAD

**Issue by SN4T14** [graysky2/streamzap#1]
Pretty much what the title says, it's standard to end folder paths with "/" to make it obvious that it's referencing a folder and not a file. Not ending folder paths with "/" is especially confusing for newcomers to Linux when they see bullet points like this:
- Place `streamzap.conf` in `/etc/lirc/lircd.conf.d`

Because they'd assume "lircd.conf.d" is a file, because files usually have extensions, and folders don't.

Changing the bullet point to look like this:
- Place `streamzap.conf` in `/etc/lirc/lircd.conf.d/`

Clears up any confusion and makes it abundantly clear that the user is supposed to put the `streamzap.conf`file inside the `/etc/lirc/lircd.conf.d/` folder.

**Comment by graysky2** [comment]
Seems reasonable.  Did I get them all?  https://github.com/graysky2/streamzap/commit/b3d79f12ad77b330cc077f52cbc5a0fdf7f36583

**Comment by SN4T14** [comment]
- For mythtv only, create a symlink in your `~/.mythtv` to `~/.lirc/mythtv` `ln -s ~/.lirc/mythtv ~/.mythtv/mythtv`

That's the only thing I spotted, aren't those two both folders? Other than that, looks like you got them all. :)

**Comment by graysky2** [comment]
Done thanks.
