### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kgoerbig** [graysky2/streamzap#2]
This isn't necessarily an issue, but what distro are you currently using? I have tried to implement your conf + instructions with rasbian + xbmc installed, and have an issue where the some buttons on the streamzap remote do not work (ie OK, menu, vol's Etc...). It works right out of the box with OSMC, however. 

My goal, however, is to build my own XBMC build without the "bulk", and more customizable. I have installed lirc, and implemented your configs, but I receive an error when trying to irw, and mode 2.

**Comment by graysky2** [comment]
Arch Linux.  Should work on any distro... not sure what your specific problem is though :frowning:

**Comment by graysky2** [comment]
Feel free to ping me here but I will close this as it's not an issue per-say.
