### ISSUE TITLE
mythtv link name issue

### ISSUE THREAD

**Issue by username-xyz** [graysky2/streamzap#4]
First, a big thank you. This info got my remote working.

I did make one change however.

In README.md you say to create a link:
ln -s ~/.lirc/mythtv ~/.mythtv/mythtv

The mythtv documentation says the file should be named "lircrc" so I did:
ln -s ~/.lirc/mythtv ~/.mythtv/lircrc

Maybe this is something mythtv changed since you created this help info?

**Comment by graysky2** [comment]
Fixed.  Thanks for pointing it out.  I'm glad you found the info useful.
